-- Winch Up :: contact-info parity
--
-- GENERATED by scripts/gen-contact-info-parity.mjs from
-- src/lib/__fixtures__/contact-info-cases.json. Do not edit by hand: edit the fixtures and
-- regenerate, or the two implementations stop being tested against the same cases.
--
-- public.contains_contact_info() has a TypeScript twin in src/lib/contact-info.ts. The database
-- is the enforcement point; the twin exists so somebody typing their phone number into a public
-- field finds out while typing rather than losing the form on submit. That only helps if they
-- agree, and this is what makes them agree.

begin;

create extension if not exists pgtap with schema extensions;
set search_path = public, extensions;

select no_plan();

-- ---------------------------------------------------------------------------
-- Blocked: these must be rejected from any public free-text field
-- ---------------------------------------------------------------------------

select ok(public.contains_contact_info('call me at 512-555-0134'),
  'blocks — plain 3-3-4 with dashes');
select ok(public.contains_contact_info('512.555.0134'),
  'blocks — dots instead of dashes');
select ok(public.contains_contact_info('(512) 555-0134'),
  'blocks — parentheses');
select ok(public.contains_contact_info('5125550134'),
  'blocks — no punctuation at all');
select ok(public.contains_contact_info('+1 512 555 0134'),
  'blocks — leading country code');
select ok(public.contains_contact_info('1-512-555-0134'),
  'blocks — leading 1 with dashes');
select ok(public.contains_contact_info('reach me on 15125550134 any time'),
  'blocks — 11-digit run inside a sentence');
select ok(public.contains_contact_info('my number is 512 555 0134 thanks'),
  'blocks — spaces, mid-sentence');
select ok(public.contains_contact_info('see https://example.com/help'),
  'blocks — explicit https URL');
select ok(public.contains_contact_info('http://towing.example'),
  'blocks — explicit http URL');
select ok(public.contains_contact_info('go to www.cheaptows.com'),
  'blocks — www prefix');
select ok(public.contains_contact_info('we are at bigtruckrecovery.com'),
  'blocks — bare domain, .com');
select ok(public.contains_contact_info('find us at recovery.net, open late'),
  'blocks — bare domain followed by a comma');
select ok(public.contains_contact_info('book at quicktow.io?ref=fb'),
  'blocks — bare domain with a query string');
select ok(public.contains_contact_info('visit MyShop.SHOP now'),
  'blocks — uppercase TLD, case-insensitive match');
select ok(public.contains_contact_info('contact 999999999999'),
  'blocks — 12-digit run');

-- ---------------------------------------------------------------------------
-- Allowed: ordinary description a stuck driver would actually type
-- ---------------------------------------------------------------------------

select ok(not public.contains_contact_info(''),
  'allows — empty string');
select ok(not public.contains_contact_info('Stuck in mud past the hubs'),
  'allows — ordinary description');
select ok(not public.contains_contact_info('Buried to the frame off FM 1431'),
  'allows — road number, only 4 digits');
select ok(not public.contains_contact_info('2019 Ford F-250, 35 inch tires'),
  'allows — year and size, no phone shape');
select ok(not public.contains_contact_info('About 200 yards past the second gate'),
  'allows — distance');
select ok(not public.contains_contact_info('I have 35s and a winch'),
  'allows — short digit run');
select ok(not public.contains_contact_info('Need a tractor, truck is 8000 lb'),
  'allows — 4-digit weight');
select ok(not public.contains_contact_info('Water is maybe 18 inches deep'),
  'allows — measurement');
select ok(not public.contains_contact_info('Off CR 340 near the river crossing'),
  'allows — county road');
select ok(not public.contains_contact_info('Took 45 minutes to get here'),
  'allows — duration');
select ok(not public.contains_contact_info('Mike with the blue Jeep'),
  'allows — a name');
select ok(not public.contains_contact_info('Rained 3 days straight so it is soft'),
  'allows — digits with words');

select ok(not public.contains_contact_info(null), 'null is treated as clean');

select * from finish();
rollback;
