-- Winch Up M1 :: helper functions
--
-- Everything here is internal (schema `app`) except `public.contains_contact_info`, which is used
-- inside CHECK constraints and therefore has to be executable by whoever performs the insert.

set search_path = public, extensions;

-- ---------------------------------------------------------------------------
-- Public text hygiene
-- ---------------------------------------------------------------------------

-- True when the text looks like it carries a phone number or a URL.
-- Used as a CHECK on every free-text column that can be shown publicly, so that a requester
-- cannot route around "phones are private" by typing their number into the notes field, and a
-- tow company cannot drop a link into the public board.
create or replace function public.contains_contact_info(p_text text)
returns boolean
language sql
immutable
parallel safe
as $$
  select case
    when p_text is null then false
    -- 3-3-4 phone shapes, with or without punctuation or a leading 1
    when p_text ~ '(\+?1[ .-]?)?\(?[0-9]{3}\)?[ .-]?[0-9]{3}[ .-]?[0-9]{4}' then true
    -- any run of 10+ digits
    when p_text ~ '[0-9]{10,}' then true
    -- explicit URLs
    when p_text ~* '(https?://|www\.)' then true
    -- bare domains in the TLDs people actually paste
    when p_text ~* '[a-z0-9][a-z0-9-]*\.(com|net|org|io|co|us|info|biz|me|link|tv|shop)(/|\?|$|[ ,.;])' then true
    else false
  end;
$$;

comment on function public.contains_contact_info(text) is
  'CHECK-constraint guard: rejects phone numbers and URLs in public free-text fields.';

grant execute on function public.contains_contact_info(text) to anon, authenticated, service_role;

-- ---------------------------------------------------------------------------
-- Identifiers
-- ---------------------------------------------------------------------------

-- 24 URL-safe characters, 144 bits of entropy. This is the only thing protecting /r/[token],
-- so it must stay generated by the database and never derived from anything guessable.
create or replace function app.gen_public_token()
returns text
language sql
volatile
set search_path = public, extensions, pg_temp
as $$
  select rtrim(translate(encode(extensions.gen_random_bytes(18), 'base64'), '+/', '-_'), '=');
$$;

-- Short human-speakable code for phone calls, the Facebook post and admin screens: TX-8K4M.
-- Crockford-ish alphabet: no 0/O/1/I/L to survive being read aloud over a bad connection.
create or replace function app.gen_short_code()
returns text
language plpgsql
volatile
set search_path = public, extensions, pg_temp
as $$
declare
  alphabet constant text := '23456789ABCDEFGHJKMNPQRSTUVWXYZ';
  candidate text;
  i integer;
begin
  for attempt in 1..20 loop
    candidate := 'TX-';
    for i in 1..4 loop
      candidate := candidate || substr(alphabet, 1 + floor(random() * length(alphabet))::int, 1);
    end loop;
    if not exists (select 1 from public.requests where short_code = candidate) then
      return candidate;
    end if;
  end loop;
  -- Fall back to something guaranteed unique rather than failing a request submission.
  return 'TX-' || upper(substr(replace(gen_random_uuid()::text, '-', ''), 1, 6));
end;
$$;

-- ---------------------------------------------------------------------------
-- Geo
-- ---------------------------------------------------------------------------

create or replace function app.miles_to_meters(p_miles numeric)
returns double precision
language sql
immutable
parallel safe
as $$ select (p_miles * 1609.344)::double precision; $$;

-- Deterministic ~0.5-1 mile offset used for the public board.
-- Deterministic on purpose: the blurred pin must not jitter between page loads, because a moving
-- pin would let anyone average several samples back to the real location.
create or replace function app.blur_point(p_point extensions.geography, p_seed uuid)
returns extensions.geography
language sql
immutable
parallel safe
set search_path = public, extensions, pg_temp
as $$
  select extensions.st_project(
    p_point,
    -- 800 m .. 1700 m
    (800 + (('x' || substr(md5(p_seed::text), 1, 7))::bit(28)::int % 900))::double precision,
    radians((('x' || substr(md5(p_seed::text), 9, 7))::bit(28)::int % 360)::double precision)
  );
$$;

comment on function app.blur_point(extensions.geography, uuid) is
  'Stable ~1 mile offset for public display. Never expose the exact point before acceptance.';

-- ---------------------------------------------------------------------------
-- Dispatch matching inputs
-- ---------------------------------------------------------------------------

-- Hard requirements only. Anything softer belongs in ranking, not filtering: over-constraining
-- the candidate pool is how a stuck driver ends up with zero volunteers.
create or replace function app.required_equipment(
  p_needs_tractor boolean,
  p_needs_second_truck boolean,
  p_stuck_type stuck_type,
  p_stuck_depth stuck_depth
)
returns equipment_type[]
language sql
immutable
parallel safe
set search_path = public, extensions, pg_temp
as $$
  select coalesce(array_agg(e), '{}'::equipment_type[])
  from (
    select 'tractor'::equipment_type      where coalesce(p_needs_tractor, false)
    union all
    select 'second_truck'::equipment_type where coalesce(p_needs_second_truck, false)
  ) as t(e);
$$;

-- ---------------------------------------------------------------------------
-- Identity
-- ---------------------------------------------------------------------------
--
-- `app.is_admin()` and `app.current_responder_id()` are NOT here. They read `user_roles` and
-- `responders`, and Postgres parses a `language sql` body at CREATE FUNCTION time
-- (`check_function_bodies` is on by default), so defining them before those tables exist fails
-- the whole migration. They live at the end of 20260920000400_tables.sql instead.

-- ---------------------------------------------------------------------------
-- Rate limiting
-- ---------------------------------------------------------------------------

-- Returns true when the caller is allowed to proceed, and records the hit.
-- Callers pass a namespaced key, e.g. 'request:phone:+12815550123' or 'request:ip:203.0.113.4'.
create or replace function app.check_rate_limit(p_key text, p_max integer, p_window interval)
returns boolean
language plpgsql
volatile
security definer
set search_path = public, extensions, pg_temp
as $$
declare
  hits integer;
begin
  delete from public.rate_limit_hits
   where created_at < now() - interval '24 hours';

  select count(*) into hits
    from public.rate_limit_hits
   where bucket_key = p_key
     and created_at > now() - p_window;

  if hits >= p_max then
    return false;
  end if;

  insert into public.rate_limit_hits (bucket_key) values (p_key);
  return true;
end;
$$;

-- ---------------------------------------------------------------------------
-- Triggers
-- ---------------------------------------------------------------------------

create or replace function app.set_updated_at()
returns trigger
language plpgsql
set search_path = public, extensions, pg_temp
as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

-- ---------------------------------------------------------------------------
-- Execution grants
--
-- Deny everything in `app` first, then hand back exactly the two identity helpers that RLS
-- policy expressions have to be able to call. Everything else in this schema is service-role only.
-- ---------------------------------------------------------------------------

revoke execute on all functions in schema app from public;
revoke execute on all functions in schema app from anon, authenticated;

grant execute on all functions in schema app to service_role;

-- The two identity helpers that RLS policies call are granted to anon/authenticated at the end
-- of 20260920000400_tables.sql, where they are defined.
