import * as React from "react";

import { cn } from "@/lib/utils";

/**
 * The small set of primitives the whole app is built from.
 *
 * Hand-written rather than generated by the shadcn CLI, which cannot run here yet. They follow
 * the same shape (class-merging, plain elements, no wrapper libraries), so
 * `npx shadcn@latest add ...` can extend them later without a rewrite.
 *
 * Colour and radius utilities (`bg-brand`, `text-ink-faint`, `rounded-field`, `tap-target`) come
 * from the `@theme` block in src/app/globals.css.
 */

type ButtonProps = React.ButtonHTMLAttributes<HTMLButtonElement> & {
  variant?: "primary" | "secondary" | "quiet" | "danger";
  size?: "lg" | "md";
};

export function Button({
  className,
  variant = "primary",
  size = "lg",
  ...props
}: ButtonProps) {
  return (
    <button
      className={cn(
        // text-center matters: justify-center centres the line box, not the text inside it, so a
        // label that wraps -- which Spanish does and English often does not -- left-aligns its
        // second line.
        "inline-flex w-full items-center justify-center gap-2 rounded-field text-center font-semibold",
        "transition-colors disabled:cursor-not-allowed disabled:opacity-50",
        size === "lg" ? "tap-target px-6 text-lg" : "min-h-12 px-4 text-base",
        variant === "primary" && "bg-brand text-on-brand hover:bg-brand-hover active:bg-brand-hover",
        variant === "secondary" &&
          "border-2 border-line bg-surface text-ink hover:bg-surface-sunk",
        variant === "quiet" && "text-ink-soft underline underline-offset-4",
        variant === "danger" &&
          "border-2 border-danger bg-surface text-danger hover:bg-danger-tint",
        className,
      )}
      {...props}
    />
  );
}

export function Card({ className, ...props }: React.HTMLAttributes<HTMLDivElement>) {
  return (
    <div
      className={cn("rounded-2xl border border-line bg-surface p-5", className)}
      {...props}
    />
  );
}

export function Callout({
  tone = "neutral",
  className,
  ...props
}: React.HTMLAttributes<HTMLDivElement> & {
  tone?: "neutral" | "danger" | "good" | "brand";
}) {
  return (
    <div
      className={cn(
        "rounded-xl border-l-4 p-4 text-base",
        tone === "neutral" && "border-line bg-surface-sunk",
        tone === "danger" && "border-danger bg-danger-tint",
        tone === "good" && "border-good bg-good-tint",
        tone === "brand" && "border-brand bg-brand-tint",
        className,
      )}
      {...props}
    />
  );
}

export function Field({
  label,
  hint,
  error,
  children,
  htmlFor,
}: {
  label: string;
  hint?: string;
  error?: string | null;
  children: React.ReactNode;
  htmlFor?: string;
}) {
  return (
    <div className="space-y-2">
      <label htmlFor={htmlFor} className="block text-base font-semibold">
        {label}
      </label>
      {hint ? <p className="text-sm text-ink-faint">{hint}</p> : null}
      {children}
      {error ? (
        <p role="alert" className="text-sm font-medium text-danger">
          {error}
        </p>
      ) : null}
    </div>
  );
}

const inputClasses = cn(
  "tap-target w-full rounded-field border-2 border-line bg-surface",
  "px-4 text-lg text-ink placeholder:text-ink-faint",
  "focus:border-brand focus:outline-none",
);

export function TextInput({
  className,
  ...props
}: React.InputHTMLAttributes<HTMLInputElement>) {
  return <input className={cn(inputClasses, className)} {...props} />;
}

export function TextArea({
  className,
  ...props
}: React.TextareaHTMLAttributes<HTMLTextAreaElement>) {
  return (
    <textarea
      className={cn(inputClasses, "min-h-28 py-3 leading-relaxed", className)}
      {...props}
    />
  );
}

/**
 * Big tappable choice, used instead of a native select everywhere.
 * A dropdown on a mid-range Android, in sunlight, with cold hands, is worse than a column of
 * large buttons.
 */
export function ChoiceList<T extends string>({
  options,
  value,
  onChange,
  columns = 1,
  name,
}: {
  options: { value: T; label: string; hint?: string }[];
  value: T | null;
  onChange: (value: T) => void;
  columns?: 1 | 2;
  name: string;
}) {
  return (
    <div
      role="radiogroup"
      aria-label={name}
      className={cn("grid gap-3", columns === 2 && "grid-cols-2")}
    >
      {options.map((option) => {
        const selected = value === option.value;
        return (
          <button
            key={option.value}
            type="button"
            role="radio"
            aria-checked={selected}
            onClick={() => onChange(option.value)}
            className={cn(
              "tap-target rounded-field border-2 px-4 py-3 text-left text-lg font-medium transition-colors",
              selected
                ? "border-brand bg-brand-tint text-ink"
                : "border-line bg-surface hover:bg-surface-sunk",
            )}
          >
            <span className="block">{option.label}</span>
            {option.hint ? (
              <span className="mt-0.5 block text-sm font-normal text-ink-faint">
                {option.hint}
              </span>
            ) : null}
          </button>
        );
      })}
    </div>
  );
}

export function Toggle({
  checked,
  onChange,
  label,
  hint,
}: {
  checked: boolean;
  onChange: (next: boolean) => void;
  label: string;
  hint?: string;
}) {
  return (
    <button
      type="button"
      role="switch"
      aria-checked={checked}
      onClick={() => onChange(!checked)}
      className={cn(
        "tap-target flex w-full items-center justify-between gap-4 rounded-field border-2 px-4 py-3 text-left",
        checked ? "border-brand bg-brand-tint" : "border-line bg-surface",
      )}
    >
      <span>
        <span className="block text-lg font-medium">{label}</span>
        {hint ? <span className="block text-sm text-ink-faint">{hint}</span> : null}
      </span>
      <span
        aria-hidden
        className={cn(
          "flex h-8 w-14 shrink-0 items-center rounded-full border-2 p-1 transition-colors",
          checked ? "border-brand bg-brand" : "border-line bg-surface-sunk",
        )}
      >
        <span
          className={cn(
            "block h-5 w-5 rounded-full transition-transform",
            checked ? "translate-x-6 bg-white" : "translate-x-0 bg-ink-faint",
          )}
        />
      </span>
    </button>
  );
}

export function Checkbox({
  checked,
  onChange,
  children,
  id,
}: {
  checked: boolean;
  onChange: (next: boolean) => void;
  children: React.ReactNode;
  id: string;
}) {
  return (
    <label
      htmlFor={id}
      className={cn(
        "flex cursor-pointer items-start gap-3 rounded-field border-2 p-4",
        checked ? "border-brand bg-brand-tint" : "border-line",
      )}
    >
      <input
        id={id}
        type="checkbox"
        checked={checked}
        onChange={(event) => onChange(event.target.checked)}
        className="mt-1 h-6 w-6 shrink-0 accent-brand"
      />
      <span className="text-base leading-relaxed">{children}</span>
    </label>
  );
}
